### ISSUE TITLE
Settings Permissions mismatch

### ISSUE THREAD

**Issue by hgtonight** [daigo75/vanilla-logger#1]
The settings page links (on plugin list and side-menu) both check against the 'Garden.Settings.Manage' permission while the actual settings page checks against the 'Plugins.Logger.Manage' permission.

**Comment by daigo75** [comment]
Thanks for reporting it. It must be one of those minor issues I would not have noticed, since the Logger settings page doesn't actually do much, and since the logging is usually set up by a Super Admin (who has all permissions) once, and then "forgotten". :)

**Comment by daigo75** [comment]
Fixed in v14.06.09.001.
